app {
  server {
    host = "0.0.0.0"
    host = ${?HOST}
    port = 8010
    port = ${?PORT}
  }
  db {
    url      = "jdbc:postgresql://localhost:5432/postgres"
    url      = ${?DB_URL}
    user     = "postgres"
    user     = ${?DB_USER}
    password = "postgres"
    password = ${?DB_PASSWORD}
    driver   = "org.postgresql.Driver"
  }
}