app {
  server {
    host = "0.0.0.0"
    host = ${?HOST}
    port = 8080
    port = ${?PORT}
  }
  db {
    url      = "jdbc:postgresql://postgres:5432/banking_db"
    url      = ${?DB_URL}
    user     = "banking_user"
    user     = ${?DB_USER}
    password = "banking_secure_password"
    password = ${?DB_PASSWORD}
    driver   = "org.postgresql.Driver"
  }
}